@startuml
[*] --> Placeholder

asteriskStart --> asteriskExtensionsExists : Any
asteriskExtensionsExists --> asteriskExtensionsCheck : True
asteriskExtensionsCheck --> asteriskSipExists : True
asteriskExtensionsCheck --> asteriskExtensionsPermissions : False
asteriskExtensionsPermissions --> asteriskExtensionsEOF : Any
asteriskExtensionsEOF --> asteriskExtensionsFix : Any
asteriskExtensionsFix --> asteriskStop : Any
asteriskStop --> asteriskRunningAux : Any
asteriskSipExists --> asteriskSipCheck : True
asteriskSipCheck --> asteriskRunning : True
asteriskExtensionsExists --> asteriskRunningAux : False
asteriskSipExists --> asteriskRunningAux : False
asteriskRunningAux --> asteriskExtensionsExists : True
asteriskSipCheck --> asteriskSipPermissions : False
asteriskSipPermissions --> asteriskSipSubCheck01 : Any
asteriskSipSubCheck01 --> asteriskSipSubCheck02 : True
asteriskSipSubCheck02 --> asteriskSipSubCheck03 : True
asteriskSipSubCheck03 --> asteriskSipSubCheck04 : True
asteriskSipSubCheck04 --> asteriskSipSubCheck05 : True
asteriskSipSubCheck01 --> asteriskSipFix01 : False
asteriskSipFix01 --> asteriskSipSubCheck01 : Any
asteriskSipSubCheck02 --> asteriskSipFix02 : False
asteriskSipFix02 --> asteriskSipSubCheck02 : Any
asteriskSipSubCheck03 --> asteriskSipFix03 : False
asteriskSipFix03 --> asteriskSipSubCheck03 : Any
asteriskSipSubCheck04 --> asteriskSipFix04 : False
asteriskSipFix04 --> asteriskSipSubCheck04 : Any
asteriskSipSubCheck05 --> asteriskSipFix05 : False
asteriskSipSubCheck05 --> asteriskStop : True
asteriskSipFix05 --> asteriskSipSubCheck05 : Any

dhcpcdStart --> dhcpcdConfExists : Any
dhcpcdConfExists --> dhcpcdConfCheck : True
dhcpcdConfCheck --> dhcpcdRunning : True
dhcpcdConfCheck --> dhcpcdConfPermissions : False
dhcpcdConfPermissions --> dhcpcdConfFix : Any
dhcpcdConfFix --> dhcpcdStop : Any
dhcpcdStop --> dhcpcdRunningAux : Any
dhcpcdConfExists --> dhcpcdRunningAux : False
dhcpcdRunningAux --> dhcpcdConfExists : True

isc_dhcpStart --> isc_dhcp_serverConfExists : Any
isc_dhcp_serverConfExists --> isc_dhcp_serverConfCheck : True
isc_dhcp_serverConfExists --> isc_dhcp_serverRunningAux : False
isc_dhcp_serverRunningAux --> isc_dhcp_serverConfExists : True
isc_dhcp_serverConfCheck --> isc_dhcp_serverRunning : True
isc_dhcp_serverConfCheck --> isc_dhcp_serverConfPermissions : False
isc_dhcp_serverConfPermissions --> isc_dhcp_serverConfFix : Any
isc_dhcp_serverConfFix --> isc_dhcp_serverStop : Any
isc_dhcp_serverStop --> isc_dhcp_serverRunningAux : Any
isc_dhcp_serverRunning --> isc_dhcp_restartScriptExists : Any
isc_dhcp_restartScriptExists --> isc_dhcp_restartScriptCheck : True
isc_dhcp_restartScriptExists --> isc_dhcp_restartRunningAux : False
isc_dhcp_restartConfExists --> isc_dhcp_restartRunningAux : False
isc_dhcp_restartRunningAux --> isc_dhcp_restartScriptExists : True
isc_dhcp_restartScriptCheck --> isc_dhcp_restartConfExists : True
isc_dhcp_restartScriptCheck --> isc_dhcp_restartScriptPermissions : False
isc_dhcp_restartScriptPermissions --> isc_dhcp_restartScriptFix : Any
isc_dhcp_restartScriptFix --> isc_dhcp_restartStop : Any
isc_dhcp_restartStop --> isc_dhcp_restartRunningAux : Any
isc_dhcp_restartConfExists --> isc_dhcp_restartConfCheck : True
isc_dhcp_restartConfCheck --> isc_dhcp_restartRunning : True
isc_dhcp_restartConfCheck --> isc_dhcp_restartConfPermissions : False
isc_dhcp_restartConfPermissions --> isc_dhcp_restartConfFix : Any
isc_dhcp_restartConfFix --> isc_dhcp_restartDaemonReload : Any
isc_dhcp_restartDaemonReload --> isc_dhcp_restartStart : Any
isc_dhcp_restartStart --> isc_dhcp_restartEnable : Any
isc_dhcp_restartEnable --> isc_dhcp_restartRestart : Any
isc_dhcp_restartRestart --> isc_dhcp_restartStop : Any

eth0Start --> eth0EthtoolCheck : Any
eth0Active --> eth0Up : False
eth0Up --> eth0EthtoolCheck : Any
eth0EthtoolCheck --> eth0_ipaCheck : True
eth0EthtoolCheck --> eth0Down : False
eth0Down --> eth0Up : Any
eth0_ipaCheck --> eth0Down : False
eth0_ipaCheck --> eth0Active : True

eth012Start --> eth012VlansExists : Any
eth012VlansExists --> eth012VlansCheck : True
eth012VlansExists --> eth012Down : False
eth012VlansCheck --> eth012EthtoolCheck : True
eth012EthtoolCheck --> eth012ipaCheck : True
eth012ipaCheck --> eth012Active : True
eth012VlansCheck --> eth012VlansPermissions : False
eth012EthtoolCheck --> eth012Down : False
eth012ipaCheck --> eth012Down : False
eth012VlansPermissions --> eth012VlansFix : Any
eth012VlansFix --> eth012Down : Any
eth012Down --> eth012Up : Any
eth012Up --> eth012wait : Any
eth012wait --> eth012VlansExists : Any
eth012Active --> eth012Up : False

eth013Start --> eth013InterfacesExists : Any
eth013InterfacesExists --> eth013InterfacesCheck : True
eth013InterfacesExists --> eth013Down : False
eth013InterfacesCheck --> eth013EthtoolCheck : True
eth013EthtoolCheck --> eth013ipaCheck : True
eth013ipaCheck --> eth013Active : True
eth013InterfacesCheck --> eth013InterfacesPermissions : False
eth013InterfacesPermissions --> eth013InterfacesFix : Any
eth013InterfacesFix --> eth013Down : Any
eth013EthtoolCheck --> eth013Down : False
eth013ipaCheck --> eth013Down : False
eth013Down --> eth013Up : Any
eth013Active --> eth013Up : False
eth013Up --> eth013wait : Any
eth013wait --> eth013InterfacesExists : Any

@enduml